spring:
  application:
  name: Journal-App
  data:
    mongodb:
      uri: mongodb+srv://aman:VH5eDqvcuhZPVu3z@cluster0.kdm1s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
